In [5]:

import numpy as np
arr = np.array([1, 2, 3, 4, 5])
print(arr)

[1 2 3 4 5]


In [ ]:
# Create 1D array
import numpy as np
arr1 = np.array([1, 2, 3, 4, 5])
arr2 = np.array([6, 7, 8, 9, 10])
print(arr1)
print(type(arr1))
print(arr1.shape)

# reshape 1D array to 2D array

print("Reshape 1D array to 2D array : ")
arr1_reshaped = arr1.reshape(5, 1 )
print(arr1_reshaped)
print(arr1_reshaped.shape)  

[1 2 3 4 5]
<class 'numpy.ndarray'>
(5,)
Reshape 1D array to 2D array : 
[[1 2 3 4 5]]
(1, 5)


In [15]:
# create 2D array
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(arr2d)
print(arr2d.shape)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
(3, 3)


In [14]:
# create 2D array
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(arr2d)
print(arr2d.shape)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
(3, 3)


In [22]:
 # arange function - create array with a range of values
arr_range = np.arange(0, 10, 2).reshape(5, 1)
print(arr_range)

[[0]
 [2]
 [4]
 [6]
 [8]]


In [23]:
# identity matrix
identity_matrix = np.eye(4)
print(identity_matrix)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [ ]:
np.ones((3, 4)) # create 3x4 array of ones

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [26]:
arr = np.array([1, 2, 3, 4, 5])
print( "Array: ", arr)
print("Shape: ", arr.shape)
print("Data type: ", arr.dtype)
print("Number of dimensions: ", arr.ndim)   
print("Size: ", arr.size)
print("Item size: ", arr.itemsize, "bytes")    

Array:  [1 2 3 4 5]
Shape:  (5,)
Data type:  int64
Number of dimensions:  1
Size:  5
Item size:  8 bytes


In [28]:
# numpy vectorized operations
arr1 = np.array([1, 2, 3, 4, 5])
arr2 = np.array([6, 7, 8, 9, 10])
print("Element-wise addition: ", arr1 + arr2)
print("Element-wise multiplication: ", arr1 * arr2)
print("Element-wise subtraction: ", arr1 - arr2 )
print("Element-wise division: ", arr1 / arr2 )

Element-wise addition:  [ 7  9 11 13 15]
Element-wise multiplication:  [ 6 14 24 36 50]
Element-wise subtraction:  [-5 -5 -5 -5 -5]
Element-wise division:  [0.16666667 0.28571429 0.375      0.44444444 0.5       ]


In [29]:
# universal functions (ufuncs)
arr = np.array([1, 2, 3, 4, 5])
print("Square root: ", np.sqrt(arr))
print("Exponential: ", np.exp(arr))     

# sin and cos functions
print("Sine: ", np.sin(arr))
print("Cosine: ", np.cos(arr))  

# natural logarithm
print("Natural logarithm: ", np.log(arr))   

Square root:  [1.         1.41421356 1.73205081 2.         2.23606798]
Exponential:  [  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591 ]
Sine:  [ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427]
Cosine:  [ 0.54030231 -0.41614684 -0.9899925  -0.65364362  0.28366219]
Natural logarithm:  [0.         0.69314718 1.09861229 1.38629436 1.60943791]


In [38]:
# Array slicing and indexing
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10], [11, 12, 13, 14, 15]])
print("First row: ", arr[0])
print("Last row: ", arr[-1])
print("First column: ", arr[:, 0])
print("Last column: ", arr[:, -1])
print("Submatrix: ", arr[1:3, 1:4])

print("0th position: ", arr[0, 0]) 
print("1st position: ", arr[0, 1])
print("3rd row 4th position: ", arr[2, 3])
print("3rd position: ", arr[0, 3])

print("Array before modification: ", arr)
arr[0, 0] = 100
print("Array after modification: ", arr)

First row:  [1 2 3 4 5]
Last row:  [11 12 13 14 15]
First column:  [ 1  6 11]
Last column:  [ 5 10 15]
Submatrix:  [[ 7  8  9]
 [12 13 14]]
0th position:  1
1st position:  2
3rd row 4th position:  14
3rd position:  4
Array before modification:  [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]
Array after modification:  [[100   2   3   4   5]
 [  6   7   8   9  10]
 [ 11  12  13  14  15]]


In [42]:
print(arr[1:, 1:3])

[[ 7  8]
 [12 13]]


In [43]:
# statistics concepts -- normalization, standardization, mean, median, mode, variance, standard deviation
data = np.array([1, 2, 3, 4, 5])

# Calculate mean, median, variance
print("Mean: ", np.mean(data))

print("Median: ", np.median(data))
print("Variance: ", np.var(data))

# Calculate standard deviation
print("Standard deviation: ", np.std(data))

# calculate normalization
normalized_data = (data - np.min(data)) / (np.max(data) - np.min(data))
print("Normalized data: ", normalized_data)

Mean:  3.0
Median:  3.0
Variance:  2.0
Standard deviation:  1.4142135623730951
Normalized data:  [0.   0.25 0.5  0.75 1.  ]


In [ ]:
# logical Operations
data = np.array([1, 2, 3, 4, 5])

data[(data > 2) & (data    < 5)]  # Logical AND


array([3, 4])